# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: CrawlCove.CrawlCove
PackageVersion: 1.3.2
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-02
Installers:
  - Architecture: x64
    InstallerUrl: https://crawlcove.com/updates/Crawl-Cove-1.3.2-Setup.exe
    InstallerSha256: 8B4097C566AE9C9B8C0453B370725AE8A9361D7C2400242B61E9C579B2ED6B5E
ManifestType: installer
ManifestVersion: 1.12.0
